# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: YANZHANG's Portfolio
email: liyanzhang1117@foxmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi:) Here is Yanzhang's portfolio.</br>
  Want's to learn more about him? Check his <a href="http://www.oh-eureka.com">BLOG</a> or <a href="mailto:854605104@qq.com">email him</a>.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://liyanzhang.cn" # the base hostname & protocol for your site, e.g. http://example.com
github_username: yanzhanglee
logo: /images/LYZ-real.jpg
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
read_time: true
words_per_minute: 50
search_full_content: true
paginate: 10
paginate_path: /page:num/

# Build settings
markdown: kramdown
remote_theme: "mmistakes/so-simple-theme"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Site Author
author:
  name: Li Yanzhang
  picture: ./images/LYZ.png
  email: yanzhang_li@outlook.com
  links:
    - title: Instagram
      url: https://instagram.com/lyzsinsta
      icon: fab fa-instagram
    - title: GitHub
      url: https://github.com/yanzhanglee
      icon: fab fa-github-square
    - title: Blog
      url: http://www.oh-eureka.com
      icon: fab fa-blog

# Footer Links
footer_links:
  - title: Instagram
    url: https://instagram.com/lyzsinsta
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/yanzhanglee
    icon: fab fa-github-square
  - title: Blog
    url: http://www.oh-eureka.com
    icon: fab fa-blog

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # Works defaults
  - scope:
      path: "_works"
      type: works
    values:
      layout: post
      comments: true
      share: true

# Collections
collections:
  works:
    output: true
    permalink: /:collection/:path/

copyright: "This site is made with by *Yanzhang*."

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
