# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Yanzhang's Portfolio
email: liyanzhang1117@foxmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi:) Here is Yanzhang's portfolio.
  Want's to learn more about him? Check his BLOG on http://www.oh-eureka.com .
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://liyanzhang.cn" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  yanzhanglee
logo: /images/LYZ.png

read_time: true
words_per_minute: 100

search_full_content: true

# Build settings
markdown: kramdown
remote_theme: "mmistakes/so-simple-theme"
plugins:
  - jekyll-feed

# Site Author
author:
  name: Li Yanzhang
  picture: ./images/liyanzhang-photo.jpg
  email: liyanzhang1117@foxmail.com
  links:
    - title: Instagram
      url: https://instagram.com/lyzsinsta
      icon: fab fa-instagram
    - title: GitHub
      url: https://github.com/yanzhanglee
      icon: fab fa-github-square
    - title: Blog
      url: http://www.oh-eureka.com
      icon: fas fa-blog

# Footer Links
footer_links:
  - title: Instagram
    url: https://instagram.com/lyzsinsta
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/yanzhanglee
    icon: fab fa-github-square
  - title: Blog
    url: http://www.oh-eureka.com
    icon: fas fa-blog

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
